document.writeln("<ul>");
document.writeln("        <li><a class=\'active\' href=\'https://xiarimao.github.io/aspet.github.io/\'>主页</a></li>");
document.writeln("        <li><a href=\'#news\'>社区</a></li>");
document.writeln("        <div class=\'dropdown\'>");
document.writeln("          <a href=\'#\' class=\'dropbtn\'>工具</a>");
document.writeln("          <div class=\'dropdown-content\'>");
document.writeln("            <a href=\'#\'>游戏</a>");
document.writeln("            <a href=\'https://xiarimao.github.io/aspet.github.io/aspet-wiki.html\'>WIKI</a>");
document.writeln("            <a href=\'#\'>影视</a>");
document.writeln("            <a href=\'#\'>音乐</a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <li><a class=\'active\' href=\'#home\'>我的</a></li>");
document.writeln("      </ul>");
