document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <script type=\'text/javascript\'>");
document.writeln("        var system ={};  ");
document.writeln("           var p = navigator.platform;       ");
document.writeln("           system.win = p.indexOf(\'Win\') == 0;  ");
document.writeln("           system.mac = p.indexOf(\'Mac\') == 0;  ");
document.writeln("           system.x11 = (p == \'X11\') || (p.indexOf(\'Linux\') == 0);     ");
document.writeln("           if(system.win||system.mac||system.xll){//如果是电脑跳转到");
document.writeln("                   window.location.href=\'https://xiarimao.github.io/aspet.github.io/home.html\';  ");
document.writeln("           }else{  //如果是手机,跳转到");
document.writeln("                  window.location.href=\'https://xiarimao.github.io/aspet.github.io/mobiledevice.html\';  ");
document.writeln("           }");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("</html>");
